--
-- PostgreSQL database dump
--

\restrict qweakNRmgvR5S5m0sAFjHjc7ayfzy538UtkuPkr0VSFHwyFXHeF8WZdYdFfKoF1

-- Dumped from database version 17.9
-- Dumped by pg_dump version 17.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: attendance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attendance (
    id bigint NOT NULL,
    check_in time(6) without time zone,
    check_out time(6) without time zone,
    created_at timestamp(6) without time zone,
    date date,
    hours_worked double precision NOT NULL,
    notes text,
    status character varying(255),
    staff_id bigint NOT NULL
);


ALTER TABLE public.attendance OWNER TO postgres;

--
-- Name: attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(255),
    created_at timestamp(6) without time zone,
    details text,
    ip_address character varying(255),
    status character varying(255),
    user_email character varying(255),
    user_name character varying(255),
    user_role character varying(255)
);


ALTER TABLE public.audit_logs OWNER TO postgres;

--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bookings (
    id bigint NOT NULL,
    amount double precision NOT NULL,
    booking_date date,
    created_at timestamp(6) without time zone,
    environmental_tax double precision NOT NULL,
    payment_method character varying(255),
    processing_fee double precision NOT NULL,
    ref_no character varying(255),
    status character varying(255),
    time_slot character varying(255),
    service_id bigint NOT NULL,
    staff_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT bookings_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CASH'::character varying, 'PAYMAYA'::character varying])::text[]))),
    CONSTRAINT bookings_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CHECKED_IN'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.bookings OWNER TO postgres;

--
-- Name: bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventory (
    id bigint NOT NULL,
    category character varying(255),
    created_at timestamp(6) without time zone,
    current_stock integer NOT NULL,
    expiry_date date,
    product_name character varying(255) NOT NULL,
    reorder_level integer NOT NULL,
    status character varying(255),
    unit_cost double precision NOT NULL,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.inventory OWNER TO postgres;

--
-- Name: inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payroll; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payroll (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    cutoff_end date,
    cutoff_start date,
    deductions double precision NOT NULL,
    gross_pay double precision NOT NULL,
    hourly_rate double precision NOT NULL,
    hours_worked double precision NOT NULL,
    net_pay double precision NOT NULL,
    status character varying(255),
    staff_id bigint NOT NULL
);


ALTER TABLE public.payroll OWNER TO postgres;

--
-- Name: payroll_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payroll ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payroll_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.review_comments (
    review_id bigint NOT NULL,
    comment text
);


ALTER TABLE public.review_comments OWNER TO postgres;

--
-- Name: reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    rating integer NOT NULL,
    responded boolean NOT NULL,
    response text,
    service_name character varying(255),
    text text,
    user_id bigint NOT NULL
);


ALTER TABLE public.reviews OWNER TO postgres;

--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services (
    id bigint NOT NULL,
    active boolean NOT NULL,
    category character varying(255),
    created_at timestamp(6) without time zone,
    description text,
    duration_minutes integer NOT NULL,
    name character varying(255) NOT NULL,
    price double precision NOT NULL
);


ALTER TABLE public.services OWNER TO postgres;

--
-- Name: services_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    email_notifications boolean NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255) NOT NULL,
    phone character varying(255),
    role character varying(255) NOT NULL,
    seed_phrase_hash character varying(255),
    sms_notifications boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    verified boolean NOT NULL,
    otp_code character varying(255),
    otp_expiry timestamp(6) without time zone,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MANAGER'::character varying, 'STAFF'::character varying, 'CUSTOMER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: attendance; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.attendance (id, check_in, check_out, created_at, date, hours_worked, notes, status, staff_id) FROM stdin;
36	08:55:00	18:05:00	2026-05-12 10:44:55.370379	2026-04-16	0	\N	PRESENT	361
37	08:50:00	18:00:00	2026-05-12 10:44:55.377237	2026-04-16	0	\N	PRESENT	362
\.


--
-- Data for Name: audit_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.audit_logs (id, action, created_at, details, ip_address, status, user_email, user_name, user_role) FROM stdin;
120	Login Failed	2026-05-12 10:44:53.81132	\N	127.0.0.1	failed	admin	Unknown	unknown
121	Login Success	2026-05-12 10:44:58.990825	\N	127.0.0.1	success	admin	System Administrator	ADMIN
\.


--
-- Data for Name: bookings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bookings (id, amount, booking_date, created_at, environmental_tax, payment_method, processing_fee, ref_no, status, time_slot, service_id, staff_id, user_id) FROM stdin;
78	2500	2026-05-12	2026-05-12 10:44:55.320475	15	CASH	0	\N	CONFIRMED	10:00 AM	142	361	364
79	4500	2026-05-12	2026-05-12 10:44:55.328683	15	CASH	0	\N	COMPLETED	10:00 AM	144	362	364
80	850	2026-05-12	2026-05-12 10:44:55.334612	15	CASH	0	\N	CONFIRMED	10:00 AM	143	361	365
\.


--
-- Data for Name: inventory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventory (id, category, created_at, current_stock, expiry_date, product_name, reorder_level, status, unit_cost, updated_at) FROM stdin;
\.


--
-- Data for Name: payroll; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payroll (id, created_at, cutoff_end, cutoff_start, deductions, gross_pay, hourly_rate, hours_worked, net_pay, status, staff_id) FROM stdin;
44	2026-05-12 10:44:55.358238	2026-04-30	2026-04-16	1000	12000	150	80	11000	PROCESSED	361
45	2026-05-12 10:44:55.363829	2026-04-30	2026-04-16	900	11250	150	75	10350	PAID	362
\.


--
-- Data for Name: review_comments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.review_comments (review_id, comment) FROM stdin;
\.


--
-- Data for Name: reviews; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reviews (id, created_at, rating, responded, response, service_name, text, user_id) FROM stdin;
82	2026-05-12 10:44:55.338584	5	f	\N	Royal Hair Spa	The Royal Hair Spa was incredible. My hair has never felt this soft!	364
83	2026-05-12 10:44:55.352621	5	f	\N	Diamond Facial	The Diamond Facial literally changed my skin. Highly recommend Isabella.	365
\.


--
-- Data for Name: services; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.services (id, active, category, created_at, description, duration_minutes, name, price) FROM stdin;
142	t	Hair Care	2026-05-12 10:44:55.298132	Deep conditioning with essential oils.	90	Royal Hair Spa	2500
143	t	Hair Care	2026-05-12 10:44:55.306494	Precision grooming with expert styling.	45	Executive Haircut	850
144	t	Skincare	2026-05-12 10:44:55.310219	Advanced resurfacing for bright complexion.	75	Diamond Facial	4500
145	t	Wellness	2026-05-12 10:44:55.314558	Therapeutic massage with heated stones.	90	Zen Stone Massage	3200
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, created_at, email, email_notifications, first_name, last_name, password, phone, role, seed_phrase_hash, sms_notifications, updated_at, verified, otp_code, otp_expiry) FROM stdin;
357	2026-05-12 10:44:53.853894	admin	t	System	Administrator	$2b$10$mPldUS5Y16yVB1ii5AW4g.kkbRKpIssu2QtJzZNaVfgBxPg5eXWHm	+63 000 000 0000	ADMIN	\N	f	2026-05-12 10:44:53.853894	t	\N	\N
358	2026-05-12 10:44:54.006155	admin@spatify.ph	t	Admin	Spatify	$2a$10$ISkfnxOliXHxjHSDPLAdb.Mjww35KExHVPOCm.TanIGXVSuf.M1lu	+63 917 333 4444	ADMIN	\N	f	2026-05-12 10:44:54.006155	t	\N	\N
359	2026-05-12 10:44:54.174327	manager@test.com	t	Michael	Torres	$2a$10$tvBDsA5we7sdMlbhqJ8oceRmnx96kRijJxot5pTbSEVl6d45YqGFW	+63 918 111 2222	MANAGER	\N	f	2026-05-12 10:44:54.174327	t	\N	\N
360	2026-05-12 10:44:54.339885	manager@spatify.ph	t	Manager	Spatify	$2a$10$kWkfgASMMgVJJnSMj5fPA.4Lw0yHcL3nLXa.KWJ4iA4JRN55Ggv96	+63 918 333 4444	MANAGER	\N	f	2026-05-12 10:44:54.339885	t	\N	\N
361	2026-05-12 10:44:54.482514	staff@spatify.ph	t	Maria	Santos	$2a$10$9m0IG7wvfQ6B7t1xQAqNiOv2mUY9md9MMniKMeXJ0t7ehW9mommQy	+63 919 111 2222	STAFF	\N	f	2026-05-12 10:44:54.482514	t	\N	\N
362	2026-05-12 10:44:54.642192	staff1@spatify.com	t	Sophia	Reyes	$2a$10$gr6uPe0T6cRLG8KhuHO9TeGdhxOZjJ8VBXIgE86USImAd026MIyX6	+63 900 111 2222	STAFF	\N	f	2026-05-12 10:44:54.642192	t	\N	\N
363	2026-05-12 10:44:54.798781	staff2@spatify.com	t	John	Dela Cruz	$2a$10$sT.PVF1am41VcThYPFqX5.mA5mQMD5Pa9fQN1K1lcMW1F3UnL0p/O	+63 900 222 3333	STAFF	\N	f	2026-05-12 10:44:54.798781	t	\N	\N
364	2026-05-12 10:44:54.962675	anna@example.com	t	Anna	D.	$2a$10$CDPE7cRE5UW2rKcuQ8cnAOkRjBAtCpmWupMtD3T5VcIGG9GWZlYtW	+63 920 111 2222	CUSTOMER	\N	f	2026-05-12 10:44:54.962675	t	\N	\N
365	2026-05-12 10:44:55.119978	customer@test.com	t	Isabella	Luna	$2a$10$rhQ.lxTh9I/gsZ.ujs9cJui6ppd2CjKrHbwb5uBVBS2ywN9/7JAK2	+63 921 333 4444	CUSTOMER	\N	f	2026-05-12 10:44:55.119978	t	\N	\N
366	2026-05-12 10:44:55.294123	carlos@example.com	t	Carlos	M.	$2a$10$6NmjNt/KYo.qUZG3ZuBc5eftupXvwkxX9MCxjxMOEu55jWDVLIhCK	+63 922 111 2222	CUSTOMER	\N	f	2026-05-12 10:44:55.294123	t	\N	\N
\.


--
-- Name: attendance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.attendance_id_seq', 37, true);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.audit_logs_id_seq', 121, true);


--
-- Name: bookings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bookings_id_seq', 80, true);


--
-- Name: inventory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventory_id_seq', 11, true);


--
-- Name: payroll_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payroll_id_seq', 45, true);


--
-- Name: reviews_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reviews_id_seq', 83, true);


--
-- Name: services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.services_id_seq', 145, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 366, true);


--
-- Name: attendance attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);


--
-- Name: inventory inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_pkey PRIMARY KEY (id);


--
-- Name: payroll payroll_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payroll
    ADD CONSTRAINT payroll_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: services services_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (id);


--
-- Name: bookings uk4e5htoim4lko9p8owpgu0tlke; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT uk4e5htoim4lko9p8owpgu0tlke UNIQUE (ref_no);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: payroll fk3rl141navx3ohu4x6vfbrm04q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payroll
    ADD CONSTRAINT fk3rl141navx3ohu4x6vfbrm04q FOREIGN KEY (staff_id) REFERENCES public.users(id);


--
-- Name: review_comments fk6s1ax51thsktjrv6tqawjua9s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review_comments
    ADD CONSTRAINT fk6s1ax51thsktjrv6tqawjua9s FOREIGN KEY (review_id) REFERENCES public.reviews(id);


--
-- Name: reviews fkcgy7qjc1r99dp117y9en6lxye; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkcgy7qjc1r99dp117y9en6lxye FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: bookings fkeyog2oic85xg7hsu2je2lx3s6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fkeyog2oic85xg7hsu2je2lx3s6 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: bookings fkjcwbou2jlblfwu14uoxs65b25; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fkjcwbou2jlblfwu14uoxs65b25 FOREIGN KEY (service_id) REFERENCES public.services(id);


--
-- Name: attendance fklll60kbqve3itmat2xf4c2n11; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fklll60kbqve3itmat2xf4c2n11 FOREIGN KEY (staff_id) REFERENCES public.users(id);


--
-- Name: bookings fkq77lf1nt94ny672p97mnhhsnv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fkq77lf1nt94ny672p97mnhhsnv FOREIGN KEY (staff_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict qweakNRmgvR5S5m0sAFjHjc7ayfzy538UtkuPkr0VSFHwyFXHeF8WZdYdFfKoF1

